
const Routes = {
    loginisation: 'Auth/Login',
    register: 'Auth/Register',
    registerVolonteer: 'Auth/RegisterVolunteer',
    refresh: 'Auth/Refresh',
    logout: 'Auth/Logout',
    city: 'City',
    cityCountryId: 'City/country/{countryId}',
    country: 'Country',
    documentId: 'Document/{id}',
    document: 'Document',
    neededDocuments: 'Document/step/{stepId}/needed',
    receivedDocuments: 'Document/step/{stepId}/received',
    establishmentId: 'Establishment/{id}',
    establishment: 'Establishment',
    establishmentByType: 'Establishment/byType/{cityId}',
    establishmentByCity: 'Establishment/byCity/{cityId}',
    establishmentTypes: 'Establishment/types',
    establishmentVolonteer: 'Establishment/volonteer',
    byTypeByCity : 'byType/{typeId}/byCity/{cityId}',
    socPayout: 'api/SocialPayout',
    socPayoutId: 'api/SocialPayout/{payoutId}',
    stepId: '/Step/{id}',
    step: '/Step',
    byEstablishmentType: 'byEstablishmentType/{establishmentTypeId}',
    userId: 'User/{id}',
    user: 'User',
    userCategoryId: 'UserCategory/{id}',
    userCategory: 'UserCategory',
    volunteerId: 'Volunteer/{id}',
    volunteer: 'Volunteer',
    eventId: 'Event/{id}',
    event: 'Event',
  };
  export default Routes